name: 'Lint PHP'

inputs:
  php-version:
    description: 'Version of PHP'
    required: true
    default: 'latest'

runs:
  using: "composite"
  steps:

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}

    - run: php -v
      shell: bash

    - run: env
      shell: bash

    - name: Run check script
      run: php ${{ github.action_path }}/check.php
